appn/routes.py
import os
import psycopg2
from .app import db
from flask import render_template,Blueprint,request,session,redirect,url_for,flash
import requests,os
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,BooleanField
from wtforms.validators import InputRequired,Email,Length
from functools import wraps
from flask_sqlalchemy import SQLAlchemy
from .models import Users,Coders,Links
from .mailit import mailthecoders
from .automate import ps
from config import Config
from decouple import config
# index = Blueprint('index',__name__)
# @index.route('/index')
# def indexp():  
#     return render_template("index.html")

class LoginForm(FlaskForm):
	username = StringField('username',validators=[InputRequired()])
	password = PasswordField('password',validators=[InputRequired()])
	remember = BooleanField('remember me')

def is_logged_in(f):
	@wraps(f)
	def wrap(*args, **kwargs):
		if 'logged_in' in session:
			return f(*args, **kwargs)
		else:
			flash('Unauthorized !! Please login','danger')
			return redirect(url_for('login.loginp'))
	return wrap

home = Blueprint('/',__name__)
@home.route('/')
def homep():  
    return render_template("index.html")
    
index = Blueprint('index',__name__)
@index.route('/index')
def indexp():  
    return render_template("index.html")


add = Blueprint('add',__name__)
@add.route("/add",methods=['GET','POST'])  
def addp(): 
    return render_template("add.html")  

remuser = Blueprint('remuser',__name__)
@remuser.route("/remuser",methods=['GET','POST'])  
def remuserp(): 
    return render_template("deleteuser.html")  

remrecord = Blueprint('remrecord',__name__)
@remrecord.route("/remrecord",methods=['GET','POST'])  
def remrecordp(): 
    return render_template("deleterecord.html")  

guideline = Blueprint('guideline',__name__)
@guideline.route("/guideline")  
def guidelinep(): 
    return render_template("guideline.html") 
 

subscribe = Blueprint('subscribe',__name__)
@subscribe.route("/subscribe",methods=['GET','POST'])  
@is_logged_in
def subscribep():  
    return render_template("subscribe.html")


automation = Blueprint('automation',__name__)
@automation.route("/automation",methods=['GET','POST'])  
@is_logged_in
def automationp():  
    return render_template("automate.html")


automatedurl = Blueprint('automatedurl',__name__)
@automatedurl.route("/automatedurl",methods = ["POST","GET"])  
@is_logged_in
def automatedUrlp():
    if request.method == "POST":   
        idnum = request.form["id"]
        user=Users.query.filter_by(id=idnum).first()
        if user:
            turl=user.url
            try:
                try:
                    num=db.session.query(Links).delete()
                    db.session.commit()
                except:
                    db.session.rollback()
                finally:
                    ps(turl)
                    db.session.query(Users).filter(Users.id==idnum).delete()
                    db.session.commit()
                    flash("Automation successfull !")
                    return render_template("secret.html")
            except:
                allentries=Users.query.all()
                if allentries:
                    flash("Some error occured .Couldn't automate.")
                    return render_template("secret.html")
                else:
                    flash("URL list empty .Try requesting url from home page")
                    return render_template("secret.html")
        else:
            flash("No such entry . Check the ID in the table")
            return render_template("secret.html")
    else:
        return render_template("secret.html")

deleterecord = Blueprint('deleterecord',__name__)
@deleterecord.route("/deleterecord",methods = ["POST","GET"])  
@is_logged_in
def deleterecordp():
    if request.method == "POST":   
        idnum = request.form["id"]
        coder=Coders.query.filter_by(id=idnum).first()
        if coder:
            db.session.query(Coders).filter(Coders.id==idnum).delete()
            db.session.commit()
            return render_template("secret.html")
        else:
            flash("No such entry . Check the ID in the table")
            return render_template("secret.html")
    else:
        return render_template("secret.html")


deleteuser = Blueprint('deleteuser',__name__)
@deleteuser.route("/deleteuser",methods = ["POST","GET"])  
@is_logged_in
def deleteuserp():
    if request.method == "POST":   
        idnum = request.form["id"]
        user=Users.query.filter_by(id=idnum).first()
        if user:
            db.session.query(Users).filter(Users.id==idnum).delete()
            db.session.commit()
            return render_template("secret.html")
        else:
            flash("No such entry . Check the ID in the table")
            return render_template("secret.html")
    else:
        return render_template("secret.html")


login = Blueprint('login',__name__)
@login.route('/login',methods=['GET','POST'])
def loginp():
	formy=LoginForm()
	return render_template('login.html',form=formy)

def validate(username, password):
    completion = False
    if username == config('ADMIN_USER') and password== config('ADMIN_PASSKEY'):
        completion=True
    return completion



tologin = Blueprint('tologin',__name__)
@tologin.route('/tologin', methods=['GET', 'POST'])
def toLoginp():
    error = None
    form=LoginForm()
    try:
        if form.validate_on_submit() and request.method == 'POST':
            username = request.form['username']
            password = request.form['password']
            completion = validate(username, password)
            if completion ==False:
                error = 'Invalid Credentials. Please try again.'
                flash('Invalid Credentials. Please try again.')
                return render_template('login.html',form=form)
            else:
            	session['logged_in'] =True
            	session['username'] = username
            	return redirect(url_for('secret.secretp'))
        else:
            flash("Invalid credentials")
            return render_template('login.html',form=form)
    except:
        print("Some Error occured")
        return render_template('index.html')


secret = Blueprint('secret',__name__)
@secret.route('/secret')
@is_logged_in
def secretp():
	return render_template('secret.html')



savedetails = Blueprint('savedetails',__name__)
@savedetails.route("/savedetails",methods = ["POST","GET"])
def saveDetailsp():
    msg = "msg"
    if request.method == "POST":
        name = request.form["name"]
        email = request.form["email"]
        url = request.form["url"]
        strofurl='https://www.geeksforgeeks.org/'+url
        newrequest = requests.get(strofurl)
        if newrequest.status_code == 200:
            try:
                purl = Users.query.filter_by(url=url).first()
                if purl:
                    msg = "URL already in request list"
                else:
                    user=Users(name,email,url)
                    db.session.add(user)
                    db.session.commit()
                    msg = "URL successfully Added"
            except:
                msg="Please try adding a unique handle name"
    else:
        msg="URL requested does not belong to GFG"
    flash(msg)
    return render_template("index.html")


savecoders = Blueprint('savecoders', __name__)
@savecoders.route("/savecoders",methods = ["POST","GET"])
@is_logged_in
def savecodersp():
    msg = "msg"
    if request.method == "POST":
        try:
            name = request.form["name"]
            mail = request.form["email"]
            pmail = Coders.query.filter_by(email=mail).first()
            print(pmail)
            print("pmail")
            if pmail:
                msg = "Coder already in request list"
            else:
                print("inside")
                coder=Coders(name,mail)
                print(coder)
                print(coder)
                db.session.add(coder)
                db.session.commit()
                msg = "Coder successfully Added"
        except:
            db.session.rollback()
            msg = "Please try adding a unique handle name"
        finally:
            flash(msg)
            return render_template("secret.html")


viewcoders = Blueprint('viewcoders', __name__)
@viewcoders.route('/viewcoders')
@is_logged_in
def viewCodersp():
    rows=Coders.query.all()
    print(rows)
    return render_template("viewcoders.html",rows=rows)


view = Blueprint('view',__name__)
@view.route("/view")
def viewp():
    rows=Users.query.all()
    return render_template("view.html",rows = rows)


viewlinks = Blueprint('viewlinks',__name__)
@viewlinks.route("/viewlinks")
def viewlinksp():
    rows=Links.query.all()
    return render_template("viewlinks.html",rows = rows)



logout = Blueprint('logout',__name__)
@logout.route('/logout')
@is_logged_in
def logoutp():
    session.clear()
    flash('You are logged out','success')
    return redirect(url_for('login.loginp'))



mailall=Blueprint('mailall',__name__)
@mailall.route('/mailall')
@is_logged_in
def mailAllp():
    flag,msg=mailthecoders()
    if flag:
        msg="Mail sent"
    else:
        msg=msg
    flash(msg)
    return redirect(url_for('secret.secretp'))

appn/templates/add.html
{% extends "base.html" %}
{% block title %}
Request URL
{% endblock %}
{% block content %}
<!-- <div class="links">
        <a href="{{ url_for('index.indexp') }}">Home</a>
    </div> -->
<div class="container">
  <div>
  <form class="box" action="/savedetails" method="post">
    <h3 class ="something">Details</h3>
    <input class="inp-field" type="text" placeholder="Username" name="name" value="{{
      request.form.name }}" required="true">
     <input class="inp-field" type="email" placeholder="Email" name="email" value="{{
      request.form.email}}" required="true">
     <input class="inp-field" type="text" placeholder="Topic URL" name="url" value="{{
      request.form.url}}" required="true">
    <input class="btn btn-default" type="submit" value="Add">
    <h5 style="padding:10px"><a href="{{ url_for('guideline.guidelinep') }}"><h5>Guideline for entering topic URL</h5></a></h5>
  </form>
</div>
</div>

{% endblock %}

appn/templates/automate.html
{% extends "base.html" %}
{% block title %}
Login
{% endblock %}

{% block content %}
<!-- <div class="links">
        <a href="{{ url_for('logout.logoutp') }}">Logout</a>
    </div> -->
<div class="container">
  <div>
    <h5 style="">Do you really want to change the urls database ? </h5> 
    <form class="box" action="/automatedurl" method="post">
    <h1 style="display: inline-block;">URL_ID</h1>
    <input class="inp-field" type="text" placeholder="URL ID" name="id" value="{{
      request.form.id }}">
    <input class="btn btn-default" type="submit" value="Automate">
     <a style="text-decoration: none"class="special" href="{{ url_for('view.viewp') }}"><h5>View Requested URLs</h5></a>
  </form> 
</div>
</div>
{% endblock %}

appn/templates/base.html
<html>
    <head>
        <meta name="viewport" content="initial-scale=1, maximum-scale=1">
        {% if title %}
        <title>{{ title }} - DSAEveryDay</title>
        {% else %}
        <title>DSAEveryday</title>
        {% endif %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base.css') }}" />
    </head>
    <body>
        <!-- <div class="top" >
            <ul style="list-style-type:none;">
                <li id="left">
                        <a href="{{ url_for('index.indexp') }}">Home</a>
                </li>
            <li id ="title">
            <h3>Practice DSA Everyday with Me:</h3>
        </li>
        {% if session.logged_in %}
                <li class="right">
                        <a href="{{ url_for('logout.logoutp') }}">Logout</a>
                </li>
            {% else %}
            <li class = "right">
                        <a href="{{ url_for('index.indexp') }}">Login</a>
                </li>
            {% endif %}
            </ul>
        </div> -->
        <div class="top" >
            <ul style="list-style-type:none;">
                {% if session.logged_in %}
                    <li><a class="special" href="{{ url_for('logout.logoutp') }}">Logout</a></li>
                {% else %}
                <li>
                        <a class="special" href="{{ url_for('login.loginp') }}">Login</a></li>
                {% endif %}
                {% if active_page == "index" %}
                    <li class=home><a class="special" href="{{ url_for('secret.secretp') }}">Secret</a></li>
                    {% else %}
                    <li class=home><a class="special" href="{{ url_for('index.indexp') }}">Home</a></li>
                    {% endif %}
            <li id ="title">
            <h3>Practice DSA Everyday with Me !</h3>
        </li>
            </ul>
        </div>
       <!--  <div class="top">
            <h3>Practice DSA Everyday with Me !</h3>
        </div> -->

        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </body>
</html>

appn/templates/deleterecord.html
{% extends "base.html" %}
{% block title %}
Modify
{% endblock %}

{% block content %}
<!-- <div class="links">
        <a href="{{ url_for('logout.logoutp') }}">Logout</a>
    </div> -->
<div class="container">
  <div>
    <h5 style="">Do you really want to remove the coder ? </h5> 
    <form class="box" action="/deleterecord" method="post">
    <h1>Coder ID</h1>
    <input class="inp-field" type="text" placeholder="Coder ID" name="id" value="{{
      request.form.id }}">
    <input class="btn btn-default" type="submit" value="Delete">
    <br>
  <a href="{{ url_for('secret.secretp') }}"><h5>Back</h5></a>
  </form>
</div>

</div>
{% endblock %}

appn/templates/deleteuser.html
{% extends "base.html" %}
{% block title %}
Modify
{% endblock %}

{% block content %}
<!-- <div class="links">
        <a href="{{ url_for('logout.logoutp') }}">Logout</a>
    </div> -->
<div class="container">
  <div>
    <h5 style="">Do you really want to remove the entry ? </h5> 
    <form class="box" action="/deleteuser" method="post">
    <h1>Entry ID</h1>
    <input class="inp-field" type="text" placeholder="Entry ID" name="id" value="{{
      request.form.id }}">
    <input class="btn btn-default" type="submit" value="Delete">
    <br>
  <a href="{{ url_for('secret.secretp') }}"><h5>Back</h5></a>
  </form>
</div>

</div>
{% endblock %}

appn/templates/guideline.html
{% extends "base.html" %}

{% block content %}
<div>
  <h2>Guidelines for the Topic URL</h2> 
<div class="slinks">
<br>
	<h4>1<h4>
	<h4>Remove the https://www.geeksforgeeks.org/ part from the actual url</h4>
<h4>For eg.<br>
Actual url >>  https://www.geeksforgeeks.org/fundamentals-of-algorithms/</h4>
<h4>
	Topic URL >> fundamentals-of-algorithms/</h4>
<h4>2</h4>
	<h4>Always choose pages with a lot of content links</h4>
<h4>3</h4>
<h4>Choose urls starting with https://www.geeksforgeeks.org/ and no other</h4>
<h4>4</h4>
<h4>Make sure that the links in the page refer to articles and not another set of links</h4>
	</div>
{% endblock %}

appn/templates/index.html
{% extends "base.html" %}
{% set active_page = "index" %}
{% block content %}
<!--  <div class="links">
        <a href="{{ url_for('login.loginp') }}">Login</a>
    </div> -->
<div>
	<br><br>
<div class="slinks"><h3> 
<a class="spl" href="{{ url_for('add.addp') }}">
		>>>Request URLs</a></h3>
	</div><br>
<div class="slinks"><h3>
<a class="spl" href="{{url_for('view.viewp') }}">
		>>>Requested URLs</a></h3>
	</div><br>
<div class="slinks"><h3>
<a class="spl" href="{{ url_for('viewlinks.viewlinksp') }}">
		>>>Current Scheduled Links</a></h3>
	</div>
</div>
{% endblock %}

appn/templates/login.html
{% extends "base.html" %}
{% block title %}
Login
{% endblock %}
{% block content %}
<div class="container">
  <form class="box" action="/tologin" method="post">
    <h1>Login</h1>
    {{ form.hidden_tag()}}
    <input class="inp-field" type="text" placeholder="Username" name="username" value="{{
      request.form.username }}" required="true">
     <input class="inp-field" type="password" placeholder="Password" name="password" value="{{
      request.form.password }}" required="true">
    <input class="btn btn-default" type="submit" value="Login">
  </form>
  {% if error %}
    <p class="error"><strong>Error</strong> {{ error }}
  {% endif %}
</div>

{% endblock %}

appn/templates/secret.html
{% extends "base.html" %}
{% block content %} 
<!--  <div class="links">
        <a href="{{ url_for('logout.logoutp') }}">Logout</a>
    </div> -->
<div>   
<h2>Hi , Welcome {{session.username}}</h2> 
<div class="slinks"> 
<a class="spl" href="{{ url_for('subscribe.subscribep') }}">
<h3> >>>Add Coders</a></h3><br>  
</div>
<div class="slinks"><h3>
<a class="spl" href ="{{ url_for('automation.automationp') }}">
 >>>Automate</a></h3><br>
</div>
<div class="slinks"><h3>
<a class="spl" href ="{{ url_for('viewcoders.viewCodersp') }}">
>>>List Current Coders</a></h3><br>
</div>
<div class="slinks"><h3>
<a class="spl" href ="/mailall">
 >>>Mail the Coders</a></h3>
</div>
{% endblock %}  

appn/templates/subscribe.html
{% extends "base.html" %}
{% block title %}
Subscribe
{% endblock %}

{% block content %}
<!-- <div class="links">
        <a href="{{ url_for('logout.logoutp') }}">Logout</a>
    </div> -->
<div class="container">
  <div>
  <form class="box" action="/savecoders" method="post">
    <h1>Subscribe</h1>
    <input class="inp-field" type="text" placeholder="Username" name="name" value="{{
    request.form.name }}" required="true">
     <input class="inp-field" type="email" placeholder="email" name="email" value="{{
      request.form.email }}" required="true">
    <input class="btn btn-default" type="submit" value="Subscribe">
  </form>
</div>
</div>

{% endblock %}

appn/templates/view.html
{% extends "base.html" %}

{% block content %}
<h3>Requested URLS</h3>  
<h5>The urls which are not real or does not belong to Geekforgeeks are not added</h5>

{% if session.logged_in %}
<div class="slinks">
<a href ="{{ url_for('remuser.remuserp') }}">
<h3> >>>Remove a record</h3></a>
</div>
{% endif %}

<table border=5>  
    <thead>  
        <td>ID</td>  
        <td>Name</td>  
        <td>Email</td>  
        <td>URL</td>  
    </thead>  
      
    {% for row in rows %}  
      
        <tr>  
            <td>{{row["id"]}}</td>  
            <td>{{row["name"]}}</td>  
            <td>{{row["email"]}}</td>  
            <td>{{row["url"]}}</td>  
        </tr>  
      
    {% endfor %}  
</table>  
<br><br>  


{% endblock %}  

appn/templates/viewcoders.html
{% extends "base.html" %}

{% block content %}
<!-- <div class="links">
        <a href="{{ url_for('logout.logoutp') }}">Logout</a>
    </div>  -->
 <h3>Coders </h3>  

<!--<div class="slinks">
<a href ="{{ url_for('remrecord.remrecordp') }}">
<h3> >>>Unsubscribe a Coder</h3></a>
</div>-->
 <a href="{{ url_for('remrecord.remrecordp') }}"><h5>Delete Record</h5></a>
<hr>
<table border=5>  
    <thead>  
        <td>ID</td>   
        <td>NAME</td>
        <td>EMAIL</td>  
    </thead>  
      
    {% for row in rows %}  
        <tr>  
            <td>{{row["id"]}}</td>    
            <td>{{row["name"]}}</td>  
            <td>{{row["email"]}}</td> 
        </tr>  
      
    {% endfor %}  
</table>  
<br><br>  
  
{% endblock %}  

appn/templates/viewlinks.html
{% extends "base.html" %}

{% block content %}
<h3>URLS</h3>  
<h5>The urls which are not real or does not belong to Geekforgeeks are not added</h5>
<table border=5>  
    <thead>  
        <td>ID</td>   
        <td>URL</td>  
    </thead>  
      
    {% for row in rows %}  
      
        <tr>  
            <td>{{row["id"]}}</td>    
            <td>{{row["url"]}}</td>  
        </tr>  
      
    {% endfor %}  
</table>  
<br><br>  
  
 {% endblock %}